name: CI

on:
  push:
    paths-ignore:
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        emacs_version:
          - "24.3"
          - "25.3"
          - "26.3"
          - "27.2"
          - "28.1"
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'
    - uses: actions/checkout@v3
    - name: Setup Cask and compile lisp files
      run: 'make'
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make unit-test'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
